### ISSUE TITLE
add necessary changes to make html valid

### ISSUE THREAD

**Issue by SP-XD** [SP-XD/sp-xd.github.io#3]
Use a HTML validator like https://validator.w3.org/
and add necessary fixes

**Comment by ashishpetwal** [comment]
I would like to work on this issue!

**Comment by SP-XD** [comment]
Okay, I am assigning you

> I would like to work on this issue!

**Comment by ashishpetwal** [comment]
will be back soon!

**Comment by ashishpetwal** [comment]
should I change comments too?

**Comment by SP-XD** [comment]
> should I change comments too?

which comments?

**Comment by ashishpetwal** [comment]
Like you have used some comments on your html file like projects, etc.,in this format :-

But your html file becomes invalid for XML 1.0 mapping if you use two hyphens consecutively!

**Comment by ashishpetwal** [comment]
Like if you use two hyphens consecutively it becomes invalid for XML mapping

**Comment by SP-XD** [comment]
> Like if you use two hyphens consecutively it becomes invalid for XML mapping

I see, yes replace them with other characters or keep blank

**Comment by ashishpetwal** [comment]
Or should I use only two hyphens

**Comment by ashishpetwal** [comment]
> > Like if you use two hyphens consecutively it becomes invalid for XML mapping
> 
> I see, yes replace them with other characters or keep blank

Fine! Will use space instead of them

**Comment by Amank-root** [comment]
hi, @SP-XD I have updated the HTML file and in image tags I have left it blank (width=""  and height="") so that you can fill up whatever value you want and in some of the img tags you have not specified the alt value to so I have changed it to and (Not Found) 
check the change and if need any more help feel free to ask.
With Regards,
@amank-root

**Comment by SP-XD** [comment]
> > > Like if you use two hyphens consecutively it becomes invalid for XML mapping
> > 
> > 
> > I see, yes replace them with other characters or keep blank
> 
> Fine! Will use space instead of them

Okay

**Comment by ashishpetwal** [comment]
Hey, @SP-XD I have made the pull request kindly check it

**Comment by SP-XD** [comment]
> Hey, @SP-XD I have made the pull request kindly check it

I will check in the morning, little busy

**Comment by ashishpetwal** [comment]
> > Hey, @SP-XD I have made the pull request kindly check it
> 
> I will check in the morning, little busy

No problem

**Comment by ashishpetwal** [comment]
@SP-XD do you have time to check the PR?

**Comment by SP-XD** [comment]
> @SP-XD do you have time to check the PR?

Sorry am busy with many projects right now, please check the pr now, I have left some review #6

**Comment by ashishpetwal** [comment]
I have updated the file, kindly have a look

> > @SP-XD do you have time to check the PR?
> 
> Sorry am busy with many projects right now, please check the pr now, I have left some review #6
