### ISSUE TITLE
want to create Zoom on Hover feature on Card

### ISSUE THREAD

**Issue by yasaswini999** [SP-XD/sp-xd.github.io#7]
![image](https://user-images.githubusercontent.com/106906121/194710222-5382a9be-564b-4fa0-8159-bd7659872a63.png)
pls, assign me this issue @SP-XD 
Thank you in advance!

**Comment by SP-XD** [comment]
Could you explain more? Is the zoom effect like the ones on youtube homepage?

**Comment by yasaswini999** [comment]
@SP-XD Yes exactly! what do you think about it?

**Comment by SP-XD** [comment]
> @SP-XD Yes exactly! what do you think about it?

great idea, work on it

**Comment by yasaswini999** [comment]
@SP-XD 
hey ! after cloning repo in local machine. It was like this
even though the tags are present in index.html its are displaying
do you have any idea what went wrong?
![image](https://user-images.githubusercontent.com/106906121/194879820-25f81e95-554d-4dd3-bb11-1f631c886bfb.png)

**Comment by SP-XD** [comment]
> @SP-XD hey ! after cloning repo in local machine. It was like this even though the tags are present in index.html its are displaying do you have any idea what went wrong? ![image](https://user-images.githubusercontent.com/106906121/194879820-25f81e95-554d-4dd3-bb11-1f631c886bfb.png)

I guess, You are accessing the file just by opening the html file, You have to create a live server to run the site properly. 
Use the live server extension in vscode

**Comment by yasaswini999** [comment]
@SP-XD yep working ! Thankyou
