### ISSUE TITLE
fix the position of checkout button in project cards

### ISSUE THREAD

**Issue by SP-XD** [SP-XD/sp-xd.github.io#8]
![image](https://user-images.githubusercontent.com/69642436/194887881-fbf427c4-0dff-47ce-aeea-c085fb320635.png)

**Comment by tchar7** [comment]
Can I work on this.

**Comment by Vibrin** [comment]
After opening the site, I check the positions of the checkout button and they are not like the once in the image. Is the issue already fixed?

**Comment by SP-XD** [comment]
> Can I work on this.

Sure
